-- Migration 030: production completion rules.
-- production_item_steps: any role may toggle completion (sign-off); only
--   office/admin may insert/delete (steps are generated by RPC).
-- hardware orders: office/admin place/manage; factory may mark items 'received'
--   (but not 'ordered') via a WITH CHECK rule — no app change needed.

-- production_item_steps
alter table public.production_item_steps enable row level security;
do $$ declare r record; begin
  for r in select policyname from pg_policies where schemaname = 'public' and tablename = 'production_item_steps' loop
    execute format('drop policy if exists %I on public.production_item_steps', r.policyname);
  end loop;
end $$;
create policy "pis_select" on public.production_item_steps for select to authenticated using (true);
create policy "pis_update" on public.production_item_steps for update to authenticated using (true) with check (true);
create policy "pis_insert" on public.production_item_steps for insert to authenticated with check (public.is_office());
create policy "pis_delete" on public.production_item_steps for delete to authenticated using (public.is_office());

-- hardware_orders: read all; office/admin write (create/place orders).
alter table public.hardware_orders enable row level security;
do $$ declare r record; begin
  for r in select policyname from pg_policies where schemaname = 'public' and tablename = 'hardware_orders' loop
    execute format('drop policy if exists %I on public.hardware_orders', r.policyname);
  end loop;
end $$;
create policy "ho_select" on public.hardware_orders for select to authenticated using (true);
create policy "ho_modify" on public.hardware_orders for all to authenticated using (public.is_office()) with check (public.is_office());

-- hardware_order_items: read all; office/admin full write; factory may UPDATE
-- only to status 'received' (mark received, not place).
alter table public.hardware_order_items enable row level security;
do $$ declare r record; begin
  for r in select policyname from pg_policies where schemaname = 'public' and tablename = 'hardware_order_items' loop
    execute format('drop policy if exists %I on public.hardware_order_items', r.policyname);
  end loop;
end $$;
create policy "hoi_select" on public.hardware_order_items for select to authenticated using (true);
create policy "hoi_office_all" on public.hardware_order_items for all to authenticated using (public.is_office()) with check (public.is_office());
create policy "hoi_factory_receive" on public.hardware_order_items for update to authenticated using (public.auth_role() = 'factory') with check (status = 'received');
